// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { IstioOperatorArgs } from "./istioOperator";
export type IstioOperator = import("./istioOperator").IstioOperator;
export const IstioOperator: typeof import("./istioOperator").IstioOperator = null as any;
utilities.lazyLoad(exports, ["IstioOperator"], () => require("./istioOperator"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:install.istio.io/v1alpha1:IstioOperator":
                return new IstioOperator(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("istio", "install.istio.io/v1alpha1", _module)
